version: '3'

services:
  postgres:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bike_reservation_db
    ports:
      - 5441:5432
    volumes:
      - ./docker-postgresql-data-for-dev:/var/lib/postgresql/data
      - ./src/main/resources/bike-reservation-ddl.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/main/resources/bike-reservation-seed.sql:/docker-entrypoint-initdb.d/seed.sql